repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: requirements-sort
        name: requirements-sort
        description: "Sort the requirements.txt alphabetically"
        language: system
        entry: 'sort --output=requirements.txt'
        files: 'requirements.txt'
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
      - id: black-jupyter
        language_version: python3.11
